- rtl/serv_mpram.v
- rtl/serv_top.v
- rtl/shift_reg.v
Synopysis DC has problems with forward references and initial
statements. Fixed that for better compatibility.
> rtl: Improve compatibility with Synopsys Design Compiler

- servant/servant.v
- servant/servant_mux.v
Can't launch following command without disabling this warning : 
```
$ fusesoc run --target=verilator_tb servant --uart_baudrate=57600 --firmware=$SERV/sw/zephyr_hello.hex
INFO: Preparing ::serv:0
INFO: Preparing ::servant:0
verilator -f servant_0.vc --trace
%Warning-WIDTH: ../src/servant_0/servant/servant_mux.v:69: Logical Operator IF expects 1 bit on the If, but If's VALUEPLUSARGS 'signature=%s' generates 32 bits.
%Warning-WIDTH: Use "/* verilator lint_off WIDTH */" and lint_on around source to disable this message.
%Warning-WIDTH: ../src/servant_0/servant/servant.v:108: Logical Operator IF expects 1 bit on the If, but If's VALUEPLUSARGS 'firmware=%s' generates 32 bits.
%Error: Exiting due to 2 warning(s)
%Error: Command Failed /usr/local/bin/verilator_bin -f servant_0.vc --trace …
```
> Suppressing some verilator lint warnings

- README.md
According to servant.core --memfile must be used for all boards. When using --firmware for icebreaker, tinyfpga_bx or nexys_a7, fusesoc fails with:
INFO: Setting up project
usage: fusesoc run servant_0 [-h] [--memfile MEMFILE] [--PLL PLL]
[--memsize MEMSIZE] [--RISCV_FORMAL]
[--SERV_CLEAR_RAM] [--pnr PNR]
[--arachne_pnr_options ARACHNE_PNR_OPTIONS]
[--nextpnr_options NEXTPNR_OPTIONS]
[--yosys_synth_options YOSYS_SYNTH_OPTIONS]
fusesoc run servant_0: error: unrecognized arguments: --firmware=/sw/blinky.hex
> README: --firmware parameter only available for sim and verilator_tb targets

- README.md
The line about using memfile is after icebreaker. This location is ambiguous because it's not clear if it's only applicable to this board or if its a more generic information.
This PR move this line before board to be more generic.
> README: argument to use blinky example instead of hello world is true for all boards

- README.md
- data/arty_a7_35t.xdc
- servant.core
- servant/servix.v
- servant/servix_clock_gen.v
This board is based on an Xilinx artix 35T with a input clock 100MHz, but for an unclear reason, the UART is not working with 32MHz PLL output frequency. This is why this PR add modification to servix_clock_gen, and servant.core, to be able to select 32 or 16 MHz frequency.
> Add Arty a7 35t support

- rtl/serv_alu.v
- rtl/serv_decode.v
Both `rtl/serv_alu.v` and `rtl/serv_decode.v` references to wires/regs before they are declared.
* `eq_r` is used in `serv_alu.v` before declared.
* Both `m2` and `m3` are used in `serv_decode.v` before declared.
As a side note, I've tried to run the simulation test, and I saw one thing, the command does not run inside `workspace` but in `$SERV` instead.
Here is the result after the modifications proposed here:
`INFO: Running
INFO: Running simulation
Loading RAM from /home/diego/serv/sw/zephyr_hello.hex
***** Booting Zephyr OS zephyr-v1.14.1-4-gc7c2d62513fe *****
Hello World! service
`
Seems that Verilator is not catching all linter problems, I saw this two just by looking the source code, but there are few more that Verilator is not catching.
> Declare variables/nets before referenced

- rtl/serv_rf_ram_if.v
- rtl/serv_rf_top.v
- servant/servant_ram.v
This PR add some workaround due to ISE limitations/bugs:
- Add `ifndef ISE to disable not supported $display
- move use to $clog2 with parameter affectation instead of localparam to bypass a bug.
> Add compatibility with Xilinx ISE

- README.md
- servant.core
- Add "" to nextpnr option to avoid python3 parsing error
- Update PLL out value
- Update in Readme, as now the baudrate needs to be 115200 (tested in gtkterm and minicom)
> Update alhambra board

- README.md
- data/icestick.pcf
- servant.core
I tested out serv on Lattice iCEstick Evaluation Board with HX1K FPGA. I was only able to test the blinky program since HX1K has 16 x 4kb (64kb) RAM and the register file uses about 8kb which leaves 56kb (7kB - 7168 bytes) of RAM for the program. I added appropriate fusesoc parameters so that iCEstick builds pick up blinky.hex as default with 7168-byte memsize.
I encountered one issue though which has something to do with how the unused IO is configured on HX1K and the board design. Its documented here: [iCEstick unused LED Pull-up Issue](https://github.com/soumilheble/serv/issues/1).
Let me know if this platform is worthy to be pulled into serv master repo.
Thanks
> serv on iCEstick HX1K FPGA Evaluation Board

- servant.core
Ensure vlog_tb_utils is not included in the file-set for  verilator runs.
Verilator versions < 4.030 do not implement dumpfile and dumpvar, which are used in vlog_tb_utils.
> break out verilator fileset for use with v < 4.030

- rtl/serv_decode.v
Either the input from instruction bus is registered and the
outputs are generated combinatorially (PRE_REGISTER mode), or
the input from the instruction bus is decoded combinatorially
and the result of decoding is registered (POST_REGISTER mode).
First is smaller because it allows synthesis to optimize decoding
logic with its users, but is slow. The second one is faster but
slightly bigger.
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
> decode: Add option to pre or post register during decoding

- README.md
- data/de10_nano.sdc
- data/de10_nano.tcl
- servant.core
Terasic DE10 Nano kit is a cycloneV SoC (5CSEBA6U23I7) based board
> Add support for Terasic DE10 Nano Kit

- README.md
- data/ebaz4205.xdc
- servant.core
- servant/servix_ebaz4205.v
- servant/servix_ebaz4205_clock_gen.v
References:
- https://github.com/fusesoc/blinky/pull/68/files (EBAZ4205 blinky)
- https://github.com/fusesoc/blinky#ebaz4205-development-board
- Existing 'arty_a7_35t' example
This PR also cleans up a bunch of whitespace issues (no functional change).
Picture:
> Add support for EBAZ4205 'Development' Board

- rtl/serv_decode.v
- rtl/serv_immdec.v
- rtl/serv_top.v
Update the files to fix issue #62 .
```
Modelsim tends to get quite angry when it sees a variable that is not declared.
serv_decode.v: "op_or_opimm"
serv_immdec.v: "signbit"
serv_top.v: "dbus_rdt"
```
> Vars modelsim

- README.md
- data/ax309.ucf
- servant.core
- servant/servant_ax309.v
- servant/servant_ax309_clock_gen.v
The UCF file and `servant_ax309*.v` are based on the ones from `servant_lx9*.v`, with the following functionalities:
- running at 32MHz instead of 16MHz;
- hence supporting a 115200 baud rate UART by the on-board RS232 (USB power+UART);
- the on-board `RESET` button can reset the CPU.
> Add AX309 board as a target running at 32MHz by default

- servant/ice40_pll.v
While helping gojimmypi to bring up FuseSOC Serv on a new ice40-based target we were having trouble with Serv not starting up after configuration. Digging into the clock and reset logic I discovered that the wb_rst signal generated in the ice40_pll.v module was not asserting during start up.
The existing circuit relies on the PLL lock signal to clear the reset after two clock cycles, but because the initial state of the two delay registers defaults to logic 0, the reset signal is not guaranteed to ever assert. By inverting the input and output of the 2-stage register pipeline we can ensure that at least two cycles of logic '1' are generated, thus providing a usable reset.
This change has been verified working on the icebreaker target and also on the new ice-v-wireless target that we're …
> ice40_pll.v - Guarantee at least 2 cycles of o_rst after PLL locked.

- data/arty_s7_50t.xdc
- doc/servant.rst
- servant.core
Add Servant support for the [Digilent Arty S7-50](https://digilent.com/reference/programmable-logic/arty-s7/start) based on existing Arty A7-35 implementation.
```sh
$ fusesoc run --target=arty_s7_50t servant --memfile=$SERV/sw/zephyr_hello.hex
...
INFO: SUCCESS! FPGA xc7s50csga324-1 successfully programmed with bitstream servant_1.2.1.bit.
```
```sh
$ sudo picocom /dev/ttyUSB1 --baud=57600
...
***** Booting Zephyr OS zephyr-v1.14.1-4-gc7c2d62513fe *****
Hello World! service
```
```diff
$ git diff
diff --git a/data/arty_s7_50t.xdc b/data/arty_s7_50t.xdc
index 30e799b..8c823a5 100644
--- a/data/arty_s7_50t.xdc
+++ b/data/arty_s7_50t.xdc
@@ -1,7 +1,7 @@
set_property -dict { PACKAGE_PIN R2  IOSTANDARD SSTL135  } [get_ports i_clk];   #IO_L12P_T1_MRCC_34 Sch=ddr3_clk[200]
set_property -dict { …
```
> Add Arty S7-50 support

- rtl/serv_alu.v
Currently, `serv_alu.v` uses the one-bit unsized literal `'0` which Vivado doesn't support unless a `.sv` file extension is used.
To recreate the error, run `fusesoc run --tool=vivado serv --pnr=none --part=xc7a100tcsg324-1`. Synthesis should terminate with an error.
This change resolves the Xilinx synthesis error.
> Make serv_alu.v synthesizable with Vivado

- servant/servant_timer.v
Risc-v timer is specified to be 64 bits long, meaning wraparound times of hundreds or thousands of years, making wraparound practically a non-issue. Servant has 32-bit timer, and it is not useful then timer wraps around. To avoid actually using 64 bits, this makes the timer useful even when the timer wraps around.
> Change timer wraparound behavior to be more useful

- data/machdyne_kolibri.pcf
- doc/servant.rst
- servant.core
- servant/servant_md_kolibri.v
This PR adds servant support for the Kolibri FPGA dongle:
https://github.com/machdyne/kolibri
> add support for machdyne kolibri

- README.md
The blinky test only prints out the status of the Q output when uart_baudrate is not defined. This update to README attempts to describe this condition.
> Update README.md to add blinky to pre-built test software examples

- sw/Makefile
Allow the serv software Makefile to use a different compiler prefix if defined.
> Update serv software Makefile

- data/alchitry_au.xdc
- servant.core
Add Servant support for [Alchitry Au](https://www.sparkfun.com/products/16527) platform.
```
$ fusesoc core show servant
CORE INFO
Name:        ::servant:1.2.1
Description: <No description>
Core root:   fusesoc_libraries/serv
Core file:   servant.core
Targets:
alchitry_au         : Open-hardware Alchitry AU FPGA board
. . .
$
```
```
fusesoc run --target=alchitry_au servant --uart_baudrate=57600 --memfile ./fusesoc_libraries/serv/sw/zephyr_hello.hex
. . .
Creating bitstream...
Writing bitstream ./servix.bit...
Writing bitstream ./servix.bin...
Bitstream generation completed
INFO: [Common 17-206] Exiting Vivado at Fri Jun 14 16:49:54 2024...
$
```
```
$ sudo picocom /dev/ttyUSB1 --baud=57600
picocom v3.1
Terminal ready
***** Booting Zephyr OS zephyr-v1.14.1-4-gc7c2d62513fe *****
Hello …
```
> Support for Alchitry Au platform

- data/max10_10m08evk.sdc
- data/max10_10m08evk.tcl
- doc/servant.rst
- servant.core
This commit adds support for the MAX10 10M08 Evaluation Kit
It is functional and tested on hardware (hello world message appears on TX output)
Any way to get this approved/posted in time for Teardown (June 21st)?
> added support for MAX10 10M08 Evaluation Kit

- west.yml
- zephyr/soc/riscv/servant/CMakeLists.txt
- zephyr/soc/riscv/servant/cpu_idle.c
Hi,
this PR upgrades Zephyr to 3.7.0 by updating `west.yml`. It also works around an issue introduced with Zephyr 3.6.0 regarding the use of `wfi`. This issue is tracked as #131.
Cheers!
Markus
PS: This also seems to fix https://github.com/olofk/serv/issues/113. At least, I can now run the `philosophers` demo without issues.
> Update to Zephyr 3.7.0

- west.yml
- zephyr/drivers/serial/uart_bitbang.c
- zephyr/soc/riscv/servant/Kconfig.defconfig
Hi, as usual there were some minor changes required for the next version of Zephyr, but here it is. :)
> Update to Zephyr 4.0.0

- servant.core
In `servant.core`:`targets`:`machdyne_kolibri`
> Remove duplicate `tools` entry in servant.core
